const productTypes = {
    GET_PRODUCTS: "GET_PRODUCTS",
    UPDATE_CART: "UPDATE_CART",
    GET_RATES: "GET_RATES",
    CHANGE_RATE: "CHANGE_RATE",
    CHANGE_SORT: "CHANGE_SORT",
    CHANGE_SEARCH_VALUE: "CHANGE_SEARCH_VALUE",
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCT: 'FETCH_PRODUCT',
    DELETE_PRODUCT: "DELETE_PRODUCT",
    FETCH_CHATS: 'FETCH_CHATS',
    ADD_CHAT: 'ADD_CHAT',
    DELETE_CHAT: 'DELETE_CHAT',
    FETCH_MESSAGES: 'FETCH_MESSAGES',
    ADD_MESSAGE: 'ADD_MESSAGE',
    DELETE_MESSAGE: 'DELETE_MESSAGE',
    FETCH_COMMENTS: 'FETCH_COMMENTS',
    ADD_COMMENT: 'ADD_COMMENT',
    DELETE_COMMENT: 'DELETE_COMMENT',
    CREATE_CHAT: 'CREATE_CHAT',
    ORDER_SUCCESS: 'ORDER_SUCCESS',
    ORDER_FAILURE: 'ORDER_FAILURE',
    ORDER_PLACING: 'ORDER_PLACING',
    CLEAR_COMMENTS: 'CLEAR_COMMENTS'
};

export default productTypes;
